# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AttentionMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Team_pb2 as Team__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x41ttentionMessage.proto\x12\tllsf_msgs\x1a\nTeam.proto\"\x86\x01\n\x10\x41ttentionMessage\x12\x0f\n\x07message\x18\x01 \x02(\t\x12\x14\n\x0ctime_to_show\x18\x02 \x01(\x02\x12#\n\nteam_color\x18\x03 \x01(\x0e\x32\x0f.llsf_msgs.Team\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x02\x42\x39\n\x1forg.robocup_logistics.llsf_msgsB\x16\x41ttentionMessageProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AttentionMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\026AttentionMessageProtos'
  _ATTENTIONMESSAGE._serialized_start=50
  _ATTENTIONMESSAGE._serialized_end=184
  _ATTENTIONMESSAGE_COMPTYPE._serialized_start=146
  _ATTENTIONMESSAGE_COMPTYPE._serialized_end=184
# @@protoc_insertion_point(module_scope)
