# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BeaconSignal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Time_pb2 as Time__pb2
import Team_pb2 as Team__pb2
import Pose2D_pb2 as Pose2D__pb2
import AgentTask_pb2 as AgentTask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x42\x65\x61\x63onSignal.proto\x12\tllsf_msgs\x1a\nTime.proto\x1a\nTeam.proto\x1a\x0cPose2D.proto\x1a\x0f\x41gentTask.proto\"\xb3\x02\n\x0c\x42\x65\x61\x63onSignal\x12\x1d\n\x04time\x18\x01 \x02(\x0b\x32\x0f.llsf_msgs.Time\x12\x0b\n\x03seq\x18\x02 \x02(\x04\x12\x0e\n\x06number\x18\x08 \x02(\r\x12\x11\n\tteam_name\x18\x04 \x02(\t\x12\x11\n\tpeer_name\x18\x05 \x02(\t\x12#\n\nteam_color\x18\x06 \x01(\x0e\x32\x0f.llsf_msgs.Team\x12\x1f\n\x04pose\x18\x07 \x01(\x0b\x32\x11.llsf_msgs.Pose2D\x12\"\n\x04task\x18\t \x01(\x0b\x32\x14.llsf_msgs.AgentTask\x12/\n\x0e\x66inished_tasks\x18\n \x03(\x0b\x32\x17.llsf_msgs.FinishedTask\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x01\"2\n\x0c\x46inishedTask\x12\x0e\n\x06TaskId\x18\x01 \x02(\r\x12\x12\n\nsuccessful\x18\x02 \x02(\x08\x42\x35\n\x1forg.robocup_logistics.llsf_msgsB\x12\x42\x65\x61\x63onSignalProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BeaconSignal_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\022BeaconSignalProtos'
  _BEACONSIGNAL._serialized_start=89
  _BEACONSIGNAL._serialized_end=396
  _BEACONSIGNAL_COMPTYPE._serialized_start=358
  _BEACONSIGNAL_COMPTYPE._serialized_end=396
  _FINISHEDTASK._serialized_start=398
  _FINISHEDTASK._serialized_end=448
# @@protoc_insertion_point(module_scope)
