# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExplorationInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MachineInfo_pb2 as MachineInfo__pb2
import Team_pb2 as Team__pb2
import Zone_pb2 as Zone__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x45xplorationInfo.proto\x12\tllsf_msgs\x1a\x11MachineInfo.proto\x1a\nTeam.proto\x1a\nZone.proto\"o\n\x11\x45xplorationSignal\x12\x0c\n\x04type\x18\x01 \x02(\t\x12$\n\x06lights\x18\x02 \x03(\x0b\x32\x14.llsf_msgs.LightSpec\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x46\"}\n\x0f\x45xplorationZone\x12\x1d\n\x04zone\x18\x02 \x02(\x0e\x32\x0f.llsf_msgs.Zone\x12#\n\nteam_color\x18\x03 \x02(\x0e\x32\x0f.llsf_msgs.Team\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10G\"\x93\x01\n\x0f\x45xplorationInfo\x12-\n\x07signals\x18\x01 \x03(\x0b\x32\x1c.llsf_msgs.ExplorationSignal\x12)\n\x05zones\x18\x02 \x03(\x0b\x32\x1a.llsf_msgs.ExplorationZone\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10HB8\n\x1forg.robocup_logistics.llsf_msgsB\x15\x45xplorationInfoProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExplorationInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\025ExplorationInfoProtos'
  _EXPLORATIONSIGNAL._serialized_start=79
  _EXPLORATIONSIGNAL._serialized_end=190
  _EXPLORATIONSIGNAL_COMPTYPE._serialized_start=152
  _EXPLORATIONSIGNAL_COMPTYPE._serialized_end=190
  _EXPLORATIONZONE._serialized_start=192
  _EXPLORATIONZONE._serialized_end=317
  _EXPLORATIONZONE_COMPTYPE._serialized_start=279
  _EXPLORATIONZONE_COMPTYPE._serialized_end=317
  _EXPLORATIONINFO._serialized_start=320
  _EXPLORATIONINFO._serialized_end=467
  _EXPLORATIONINFO_COMPTYPE._serialized_start=429
  _EXPLORATIONINFO_COMPTYPE._serialized_end=467
# @@protoc_insertion_point(module_scope)
