# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameState.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Time_pb2 as Time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fGameState.proto\x12\tllsf_msgs\x1a\nTime.proto\"\x91\x03\n\tGameState\x12\"\n\tgame_time\x18\x01 \x02(\x0b\x32\x0f.llsf_msgs.Time\x12)\n\x05state\x18\x03 \x02(\x0e\x32\x1a.llsf_msgs.GameState.State\x12)\n\x05phase\x18\x04 \x02(\x0e\x32\x1a.llsf_msgs.GameState.Phase\x12\x13\n\x0bpoints_cyan\x18\x05 \x01(\r\x12\x11\n\tteam_cyan\x18\x06 \x01(\t\x12\x16\n\x0epoints_magenta\x18\x08 \x01(\r\x12\x14\n\x0cteam_magenta\x18\t \x01(\t\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x14\":\n\x05State\x12\x08\n\x04INIT\x10\x00\x12\x0e\n\nWAIT_START\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\n\n\x06PAUSED\x10\x03\"P\n\x05Phase\x12\x0c\n\x08PRE_GAME\x10\x00\x12\t\n\x05SETUP\x10\n\x12\x0f\n\x0b\x45XPLORATION\x10\x14\x12\x0e\n\nPRODUCTION\x10\x1e\x12\r\n\tPOST_GAME\x10(\"a\n\x0cSetGameState\x12)\n\x05state\x18\x01 \x02(\x0e\x32\x1a.llsf_msgs.GameState.State\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x15\"a\n\x0cSetGamePhase\x12)\n\x05phase\x18\x01 \x02(\x0e\x32\x1a.llsf_msgs.GameState.Phase\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x16\"8\n\x0eRandomizeField\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x17\x42\x32\n\x1forg.robocup_logistics.llsf_msgsB\x0fGameStateProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GameState_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\017GameStateProtos'
  _GAMESTATE._serialized_start=43
  _GAMESTATE._serialized_end=444
  _GAMESTATE_COMPTYPE._serialized_start=264
  _GAMESTATE_COMPTYPE._serialized_end=302
  _GAMESTATE_STATE._serialized_start=304
  _GAMESTATE_STATE._serialized_end=362
  _GAMESTATE_PHASE._serialized_start=364
  _GAMESTATE_PHASE._serialized_end=444
  _SETGAMESTATE._serialized_start=446
  _SETGAMESTATE._serialized_end=543
  _SETGAMESTATE_COMPTYPE._serialized_start=505
  _SETGAMESTATE_COMPTYPE._serialized_end=543
  _SETGAMEPHASE._serialized_start=545
  _SETGAMEPHASE._serialized_end=642
  _SETGAMEPHASE_COMPTYPE._serialized_start=604
  _SETGAMEPHASE_COMPTYPE._serialized_end=642
  _RANDOMIZEFIELD._serialized_start=644
  _RANDOMIZEFIELD._serialized_end=700
  _RANDOMIZEFIELD_COMPTYPE._serialized_start=662
  _RANDOMIZEFIELD_COMPTYPE._serialized_end=700
# @@protoc_insertion_point(module_scope)
