# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Team_pb2 as Team__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eGameInfo.proto\x12\tllsf_msgs\x1a\nTeam.proto\"G\n\x08GameInfo\x12\x13\n\x0bknown_teams\x18\x01 \x03(\t\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10Q\"m\n\x0bSetTeamName\x12\x11\n\tteam_name\x18\x01 \x02(\t\x12#\n\nteam_color\x18\x02 \x02(\x0e\x32\x0f.llsf_msgs.Team\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10RB1\n\x1forg.robocup_logistics.llsf_msgsB\x0eGameInfoProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GameInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\016GameInfoProtos'
  _GAMEINFO._serialized_start=41
  _GAMEINFO._serialized_end=112
  _GAMEINFO_COMPTYPE._serialized_start=74
  _GAMEINFO_COMPTYPE._serialized_end=112
  _SETTEAMNAME._serialized_start=114
  _SETTEAMNAME._serialized_end=223
  _SETTEAMNAME_COMPTYPE._serialized_start=185
  _SETTEAMNAME_COMPTYPE._serialized_end=223
# @@protoc_insertion_point(module_scope)
