# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MachineInstructions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MachineDescription_pb2 as MachineDescription__pb2
import ProductColor_pb2 as ProductColor__pb2
import Team_pb2 as Team__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19MachineInstructions.proto\x12\tllsf_msgs\x1a\x18MachineDescription.proto\x1a\x12ProductColor.proto\x1a\nTeam.proto\"a\n\x14PrepareInstructionBS\x12$\n\x04side\x18\x01 \x02(\x0e\x32\x16.llsf_msgs.MachineSide\x12#\n\x05\x63olor\x18\x02 \x02(\x0e\x32\x14.llsf_msgs.BaseColor\"4\n\x14PrepareInstructionDS\x12\x10\n\x08order_id\x18\x02 \x02(\rJ\x04\x08\x01\x10\x02R\x04gate\"o\n\x14PrepareInstructionSS\x12\"\n\toperation\x18\x01 \x02(\x0e\x32\x0f.llsf_msgs.SSOp\x12\r\n\x05shelf\x18\x02 \x02(\r\x12\x0c\n\x04slot\x18\x03 \x02(\r\x12\x16\n\x0ewp_description\x18\n \x01(\t\"@\n\x14PrepareInstructionRS\x12(\n\nring_color\x18\x01 \x02(\x0e\x32\x14.llsf_msgs.RingColor\":\n\x14PrepareInstructionCS\x12\"\n\toperation\x18\x01 \x02(\x0e\x32\x0f.llsf_msgs.CSOp\"\x9c\x03\n\x0ePrepareMachine\x12#\n\nteam_color\x18\x01 \x02(\x0e\x32\x0f.llsf_msgs.Team\x12\x0f\n\x07machine\x18\x02 \x02(\t\x12\x37\n\x0einstruction_bs\x18\x04 \x01(\x0b\x32\x1f.llsf_msgs.PrepareInstructionBS\x12\x37\n\x0einstruction_ds\x18\x05 \x01(\x0b\x32\x1f.llsf_msgs.PrepareInstructionDS\x12\x37\n\x0einstruction_ss\x18\x08 \x01(\x0b\x32\x1f.llsf_msgs.PrepareInstructionSS\x12\x37\n\x0einstruction_rs\x18\x06 \x01(\x0b\x32\x1f.llsf_msgs.PrepareInstructionRS\x12\x37\n\x0einstruction_cs\x18\x07 \x01(\x0b\x32\x1f.llsf_msgs.PrepareInstructionCS\x12\x0f\n\x07sent_at\x18\x0f \x01(\x04\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x65\"l\n\x0cResetMachine\x12#\n\nteam_color\x18\x01 \x02(\x0e\x32\x0f.llsf_msgs.Team\x12\x0f\n\x07machine\x18\x02 \x02(\t\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10h*$\n\x0bMachineSide\x12\t\n\x05INPUT\x10\x01\x12\n\n\x06OUTPUT\x10\x02\x42;\n\x1forg.robocup_logistics.llsf_msgsB\x18MachineInstructionProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MachineInstructions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\030MachineInstructionProtos'
  _MACHINESIDE._serialized_start=1015
  _MACHINESIDE._serialized_end=1051
  _PREPAREINSTRUCTIONBS._serialized_start=98
  _PREPAREINSTRUCTIONBS._serialized_end=195
  _PREPAREINSTRUCTIONDS._serialized_start=197
  _PREPAREINSTRUCTIONDS._serialized_end=249
  _PREPAREINSTRUCTIONSS._serialized_start=251
  _PREPAREINSTRUCTIONSS._serialized_end=362
  _PREPAREINSTRUCTIONRS._serialized_start=364
  _PREPAREINSTRUCTIONRS._serialized_end=428
  _PREPAREINSTRUCTIONCS._serialized_start=430
  _PREPAREINSTRUCTIONCS._serialized_end=488
  _PREPAREMACHINE._serialized_start=491
  _PREPAREMACHINE._serialized_end=903
  _PREPAREMACHINE_COMPTYPE._serialized_start=865
  _PREPAREMACHINE_COMPTYPE._serialized_end=903
  _RESETMACHINE._serialized_start=905
  _RESETMACHINE._serialized_end=1013
  _RESETMACHINE_COMPTYPE._serialized_start=975
  _RESETMACHINE_COMPTYPE._serialized_end=1013
# @@protoc_insertion_point(module_scope)
