# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MachineReport.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Team_pb2 as Team__pb2
import Zone_pb2 as Zone__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13MachineReport.proto\x12\tllsf_msgs\x1a\nTeam.proto\x1a\nZone.proto\"\x89\x01\n\x12MachineReportEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x1d\n\x04zone\x18\x03 \x01(\x0e\x32\x0f.llsf_msgs.Zone\x12\x10\n\x08rotation\x18\x04 \x01(\r\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10<\"\x8d\x01\n\rMachineReport\x12#\n\nteam_color\x18\x02 \x02(\x0e\x32\x0f.llsf_msgs.Team\x12/\n\x08machines\x18\x01 \x03(\x0b\x32\x1d.llsf_msgs.MachineReportEntry\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10=\"\xb3\x01\n\x11MachineReportInfo\x12\x19\n\x11reported_machines\x18\x01 \x03(\t\x12#\n\nteam_color\x18\x02 \x02(\x0e\x32\x0f.llsf_msgs.Team\x12\x36\n\x0ereported_types\x18\x03 \x03(\x0b\x32\x1e.llsf_msgs.MachineTypeFeedback\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10>\"\x9d\x01\n\x13MachineTypeFeedback\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x1d\n\x04zone\x18\x02 \x02(\x0e\x32\x0f.llsf_msgs.Zone\x12\x0c\n\x04name\x18\x03 \x01(\t\x12#\n\nteam_color\x18\x04 \x01(\x0e\x32\x0f.llsf_msgs.Team\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10?B6\n\x1forg.robocup_logistics.llsf_msgsB\x13MachineReportProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MachineReport_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\023MachineReportProtos'
  _MACHINEREPORTENTRY._serialized_start=59
  _MACHINEREPORTENTRY._serialized_end=196
  _MACHINEREPORTENTRY_COMPTYPE._serialized_start=158
  _MACHINEREPORTENTRY_COMPTYPE._serialized_end=196
  _MACHINEREPORT._serialized_start=199
  _MACHINEREPORT._serialized_end=340
  _MACHINEREPORT_COMPTYPE._serialized_start=302
  _MACHINEREPORT_COMPTYPE._serialized_end=340
  _MACHINEREPORTINFO._serialized_start=343
  _MACHINEREPORTINFO._serialized_end=522
  _MACHINEREPORTINFO_COMPTYPE._serialized_start=484
  _MACHINEREPORTINFO_COMPTYPE._serialized_end=522
  _MACHINETYPEFEEDBACK._serialized_start=525
  _MACHINETYPEFEEDBACK._serialized_end=682
  _MACHINETYPEFEEDBACK_COMPTYPE._serialized_start=644
  _MACHINETYPEFEEDBACK_COMPTYPE._serialized_end=682
# @@protoc_insertion_point(module_scope)
