# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MachineCommands.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MachineInfo_pb2 as MachineInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15MachineCommands.proto\x12\tllsf_msgs\x1a\x11MachineInfo.proto\"w\n\x0fSetMachineState\x12\x14\n\x0cmachine_name\x18\x01 \x02(\t\x12&\n\x05state\x18\x02 \x02(\x0e\x32\x17.llsf_msgs.MachineState\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x11\"N\n\x0eMachineAddBase\x12\x14\n\x0cmachine_name\x18\x01 \x02(\t\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x12\"v\n\x10SetMachineLights\x12\x14\n\x0cmachine_name\x18\x01 \x02(\t\x12$\n\x06lights\x18\x02 \x03(\x0b\x32\x14.llsf_msgs.LightSpec\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x13*_\n\x0cMachineState\x12\x08\n\x04IDLE\x10\x01\x12\r\n\tAVAILABLE\x10\x02\x12\r\n\tPROCESSED\x10\x03\x12\r\n\tDELIVERED\x10\x04\x12\r\n\tRETRIEVED\x10\x05\x12\t\n\x05RESET\x10\x0f\x42\x38\n\x1forg.robocup_logistics.llsf_msgsB\x15MachineCommandsProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MachineCommands_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\025MachineCommandsProtos'
  _MACHINESTATE._serialized_start=376
  _MACHINESTATE._serialized_end=471
  _SETMACHINESTATE._serialized_start=55
  _SETMACHINESTATE._serialized_end=174
  _SETMACHINESTATE_COMPTYPE._serialized_start=136
  _SETMACHINESTATE_COMPTYPE._serialized_end=174
  _MACHINEADDBASE._serialized_start=176
  _MACHINEADDBASE._serialized_end=254
  _MACHINEADDBASE_COMPTYPE._serialized_start=216
  _MACHINEADDBASE_COMPTYPE._serialized_end=254
  _SETMACHINELIGHTS._serialized_start=256
  _SETMACHINELIGHTS._serialized_end=374
  _SETMACHINELIGHTS_COMPTYPE._serialized_start=336
  _SETMACHINELIGHTS_COMPTYPE._serialized_end=374
# @@protoc_insertion_point(module_scope)
