# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MachineDescription.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18MachineDescription.proto\x12\tllsf_msgs*,\n\nLightColor\x12\x07\n\x03RED\x10\x00\x12\n\n\x06YELLOW\x10\x01\x12\t\n\x05GREEN\x10\x02*(\n\nLightState\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x12\t\n\x05\x42LINK\x10\x02*0\n\x04SSOp\x12\t\n\x05STORE\x10\x01\x12\x0c\n\x08RETRIEVE\x10\x02\x12\x0f\n\x0b\x43HANGE_INFO\x10\x03*\'\n\x04\x43SOp\x12\x10\n\x0cRETRIEVE_CAP\x10\x01\x12\r\n\tMOUNT_CAP\x10\x02\x42;\n\x1forg.robocup_logistics.llsf_msgsB\x18MachineDescriptionProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MachineDescription_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\030MachineDescriptionProtos'
  _LIGHTCOLOR._serialized_start=39
  _LIGHTCOLOR._serialized_end=83
  _LIGHTSTATE._serialized_start=85
  _LIGHTSTATE._serialized_end=125
  _SSOP._serialized_start=127
  _SSOP._serialized_end=175
  _CSOP._serialized_start=177
  _CSOP._serialized_end=216
# @@protoc_insertion_point(module_scope)
