# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NavigationChallenge.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Team_pb2 as Team__pb2
import Zone_pb2 as Zone__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19NavigationChallenge.proto\x12\tllsf_msgs\x1a\nTeam.proto\x1a\nZone.proto\"y\n\x05Route\x12\n\n\x02id\x18\x01 \x02(\r\x12\x1e\n\x05route\x18\x02 \x03(\x0e\x32\x0f.llsf_msgs.Zone\x12 \n\x07reached\x18\x03 \x03(\x0e\x32\x0f.llsf_msgs.Zone\x12\"\n\tremaining\x18\x04 \x03(\x0e\x32\x0f.llsf_msgs.Zone\"\x82\x01\n\x10NavigationRoutes\x12#\n\nteam_color\x18\x01 \x02(\x0e\x32\x0f.llsf_msgs.Team\x12 \n\x06routes\x18\x05 \x03(\x0b\x32\x10.llsf_msgs.Route\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xfa\x01\x42<\n\x1forg.robocup_logistics.llsf_msgsB\x19NavigationChallengeProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NavigationChallenge_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\031NavigationChallengeProtos'
  _ROUTE._serialized_start=64
  _ROUTE._serialized_end=185
  _NAVIGATIONROUTES._serialized_start=188
  _NAVIGATIONROUTES._serialized_end=318
  _NAVIGATIONROUTES_COMPTYPE._serialized_start=279
  _NAVIGATIONROUTES_COMPTYPE._serialized_end=318
# @@protoc_insertion_point(module_scope)
