# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotCommands.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Team_pb2 as Team__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RobotCommands.proto\x12\tllsf_msgs\x1a\nTeam.proto\"\x8d\x01\n\x13SetRobotMaintenance\x12\x14\n\x0crobot_number\x18\x01 \x02(\r\x12\x13\n\x0bmaintenance\x18\x03 \x02(\x08\x12#\n\nteam_color\x18\x04 \x02(\x0e\x32\x0f.llsf_msgs.Team\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10[B6\n\x1forg.robocup_logistics.llsf_msgsB\x13RobotCommandsProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RobotCommands_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\023RobotCommandsProtos'
  _SETROBOTMAINTENANCE._serialized_start=47
  _SETROBOTMAINTENANCE._serialized_end=188
  _SETROBOTMAINTENANCE_COMPTYPE._serialized_start=150
  _SETROBOTMAINTENANCE_COMPTYPE._serialized_end=188
# @@protoc_insertion_point(module_scope)
