# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimTimeSync.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Time_pb2 as Time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11SimTimeSync.proto\x12\tllsf_msgs\x1a\nTime.proto\"\x83\x01\n\x0bSimTimeSync\x12!\n\x08sim_time\x18\x01 \x02(\x0b\x32\x0f.llsf_msgs.Time\x12\x18\n\x10real_time_factor\x18\x02 \x02(\x02\x12\x0e\n\x06paused\x18\x03 \x02(\x08\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\r\n\x08MSG_TYPE\x10\xc7\x02\x42\x34\n\x1forg.robocup_logistics.llsf_msgsB\x11SimTimeSyncProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SimTimeSync_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\021SimTimeSyncProtos'
  _SIMTIMESYNC._serialized_start=45
  _SIMTIMESYNC._serialized_end=176
  _SIMTIMESYNC_COMPTYPE._serialized_start=137
  _SIMTIMESYNC_COMPTYPE._serialized_end=176
# @@protoc_insertion_point(module_scope)
