# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VersionInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11VersionInfo.proto\x12\tllsf_msgs\"\x92\x01\n\x0bVersionInfo\x12\x15\n\rversion_major\x18\x01 \x02(\r\x12\x15\n\rversion_minor\x18\x02 \x02(\r\x12\x15\n\rversion_micro\x18\x03 \x02(\r\x12\x16\n\x0eversion_string\x18\x04 \x02(\t\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x03\x42\x30\n\x1forg.robocup_logistics.llsf_msgsB\rVersionProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VersionInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\rVersionProtos'
  _VERSIONINFO._serialized_start=33
  _VERSIONINFO._serialized_end=179
  _VERSIONINFO_COMPTYPE._serialized_start=141
  _VERSIONINFO_COMPTYPE._serialized_end=179
# @@protoc_insertion_point(module_scope)
