# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorkpieceInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Team_pb2 as Team__pb2
import ProductColor_pb2 as ProductColor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13WorkpieceInfo.proto\x12\tllsf_msgs\x1a\nTeam.proto\x1a\x12ProductColor.proto\"\x86\x02\n\tWorkpiece\x12\n\n\x02id\x18\x01 \x02(\r\x12\x12\n\nat_machine\x18\x02 \x02(\t\x12\x0f\n\x07visible\x18\x03 \x01(\x02\x12#\n\nteam_color\x18\x04 \x01(\x0e\x32\x0f.llsf_msgs.Team\x12(\n\nbase_color\x18\x05 \x01(\x0e\x32\x14.llsf_msgs.BaseColor\x12)\n\x0bring_colors\x18\x06 \x03(\x0e\x32\x14.llsf_msgs.RingColor\x12&\n\tcap_color\x18\x07 \x01(\x0e\x32\x13.llsf_msgs.CapColor\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x37\"a\n\rWorkpieceInfo\x12(\n\nworkpieces\x18\x01 \x03(\x0b\x32\x14.llsf_msgs.Workpiece\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x38\"p\n\x10WorkpieceAddRing\x12\n\n\x02id\x18\x01 \x02(\r\x12(\n\nring_color\x18\x02 \x02(\x0e\x32\x14.llsf_msgs.RingColor\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x39\x42\x36\n\x1forg.robocup_logistics.llsf_msgsB\x13WorkpieceInfoProtos')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WorkpieceInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.robocup_logistics.llsf_msgsB\023WorkpieceInfoProtos'
  _WORKPIECE._serialized_start=67
  _WORKPIECE._serialized_end=329
  _WORKPIECE_COMPTYPE._serialized_start=291
  _WORKPIECE_COMPTYPE._serialized_end=329
  _WORKPIECEINFO._serialized_start=331
  _WORKPIECEINFO._serialized_end=428
  _WORKPIECEINFO_COMPTYPE._serialized_start=390
  _WORKPIECEINFO_COMPTYPE._serialized_end=428
  _WORKPIECEADDRING._serialized_start=430
  _WORKPIECEADDRING._serialized_end=542
  _WORKPIECEADDRING_COMPTYPE._serialized_start=504
  _WORKPIECEADDRING_COMPTYPE._serialized_end=542
# @@protoc_insertion_point(module_scope)
